all: osproj2a osproj2b osproj2c
osproj2a: osproj2a.c
	g++ -lpthread  osproj2a.c -o osproj2a
osproj2b: osproj2b.c
	g++ -lpthread osproj2b.c -o osproj2b
osproj2c: osproj2c.c
	mpic++ osproj2c.c -o osrpj2c -mpe=mpilog

