/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpctime.h"

bool_t
xdr_rpctime_struct (XDR *xdrs, rpctime_struct *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->number))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->arg_array, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
