/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 
 /*
 * Programmer: Shuyi Zhao
 * Advanced Operating Systems
 * Programming Project #2: RPC program
 * Program Description: This is the client part of the RPC program, 
 * it is used to request a RPC call on a server stub. 
 * Due date: OCT 29, 2012
 * Instructor: Dr. Ajay K. Katangur
*/

/* The remote procedure itself */

#include <sys/types.h>
#include <sys/time.h>
#include <time.h>
#include "primefib.h"

//********************************************************************
//
// prime_1_svc
//
// This function computes the nth prime number.
//
// Return Value
// ------------
// result           struct that contains the nth prime number and its computing time
//
//
// Reference Parameters
// --------------------
// argp     int*     the parameter
// rqstp    svc_req*  a struct defined by the RPCgen
//
// Local Variables
// ----------------
//	result    static result_type  return result
//  number    int                 nth prime number wanted
//  test_num  int                 the candidates for looking prime number
//  i         int                 i for loop
//  is_prime  int                 check if the candidate is a prime number
//  prime_count int               check how many prime numbers have been found
//  t1        struct timeval      the beginning time
//  t2        struct timeval      the end time
//
//
//*******************************************************************
result_type *
prime_1_svc(int *argp, struct svc_req *rqstp)
{
	static result_type  result;
    int number = *argp;
    int test_num = 3;
    int i;
    int is_prime;
    int prime_count;
    
    struct timeval t1,t2;    
    gettimeofday(&t1,NULL);    
    
    if (number > 1)
    {
        prime_count = 1;
        while(prime_count < number)
        {
            is_prime = 1;
            for (i = 2; i*i <= test_num; i++)
            {   
                if (test_num%i == 0)
                {
                    is_prime = 0;
                    break;
                }
            }
            if (is_prime == 1)
               prime_count++;
            test_num++;
        } 
    }
    
    result.nth_number = test_num-1;
    gettimeofday(&t2,NULL);
    result.time = (t2.tv_sec-t1.tv_sec)*1000000+(t2.tv_usec-t1.tv_usec);

	return &result;
}

//********************************************************************
//
// fibonacci_1_svc
//
// This function computes the nth fibonacci number.
//
// Return Value
// ------------
// result           struct that contains the nth fibonacci number and its computing time
//
//
// Reference Parameters
// --------------------
// argp     int*     the parameter
// rqstp    svc_req*  a struct defined by the RPCgen
//
// Local Variables
// ----------------
// result   static result_type  the return value
// number   int                 the wanted number
// t1       struct timeval      the beginning time
// t2       struct timeval      the end time
//
//
//*******************************************************************
result_type *
fib_1_svc(int *argp, struct svc_req *rqstp)
{
	static result_type  result;
	int number = *argp;
	struct timeval t1,t2;
        
    gettimeofday(&t1,NULL);

    result.nth_number = fibonacci(number);
    
    gettimeofday(&t2,NULL);
    result.time = (t2.tv_sec-t1.tv_sec)*1000000+(t2.tv_usec-t1.tv_usec);
    
    return &result;
}

//********************************************************************
//
// fibonacci function
//
// This function computes the nth fibonacci number in a recursive way.
//
// Return Value
// ------------
// int                  returns the nth fibonacci number
//
// Value Parameters
// ----------------
// n		int			The nth fibonacci number wanted
//
//*******************************************************************
int fibonacci(int n)
{
   if ( n <= 1 )
      return n;
   return fibonacci(n-1) + fibonacci(n-2);
}





