/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/*
 * Programmer: Shuyi Zhao
 * Advanced Operating Systems
 * Programming Project #2: RPC program
 * Program Description: This is the client part of the RPC program, 
 * it is used to request a RPC call on a server stub. 
 * Due date: OCT 29, 2012
 * Instructor: Dr. Ajay K. Katangur
*/

/* The main Client program*/

#include <stdio.h>
#include <stdlib.h>
#include "primefib.h"

//********************************************************************
//
// Primefib Function
//
// This function connects a client stub to a host based on the ip address 
// using UDP. It calls the prime_1 function firstly. Then it then calls the second function fibonacci_1.
//
// Return Value
// ------------
// void                        
//
// Value Parameters
// ----------------
// number	int			                The input number
//
// Reference Parameters
// --------------------
// host     char                        The ip address of the server
//
// Local Variables
// ----------------
//	CLIENT *clnt;                       The client
//	result_type  *result_prime;         The received value from function prime
//	result_type  *result_fib;           The received value from function fib
//
//
//*******************************************************************
void
primefib_prog_1(char *host,int number)
{
	CLIENT *clnt;
	result_type  *result_prime;
	result_type  *result_fib;


#ifndef	DEBUG

    /*  A client handle is created by the RPC library routine clnt_create(). 
    This client handle is passed to the stub routine that calls the remote procedure.
    */               
	clnt = clnt_create (host, PRIMEFIB_PROG, PRIMEFIB_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    /*Client handle is passed to remote add procedure.
      The remote procedure are called exactly the same way as they are declared 
      in primefib_server.c, except for the inserted client handle as the second argument.
      It also returns a pointer to the result instead of the result
    */
	result_prime = prime_1(&number, clnt);
	if (result_prime == (result_type *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	    printf("Prime number %d is %d and the time taken is %d microseconds\n", number, result_prime->nth_number, result_prime->time);
	    
	result_fib = fib_1(&number, clnt);
	if (result_fib == (result_type *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	    printf("Fibonacci number %d is %d and the time taken is %d microseconds\n", number, result_fib->nth_number, result_fib->time);
	    
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

//********************************************************************
//
// Program Main Function
//
// This is the program main function
//
// Return Value
// ------------
// int            0 or else if it exits successfully
//
// Value Parameters
// ----------------
// argc		int		The number of arguments passed in
//
// Reference Parameters
// --------------------
// argv     char**  The arguments references
//
// Local Variables
// ----------------
// host     char**     The host name
//
//
//*******************************************************************
int
main (int argc, char *argv[])
{
	char *host;

	if (argc != 3) { 
    printf ("usage: %s server_host number_u_want \n", argv[0]); 
    exit (1); 
    }
     
    host = argv[1];
    
    primefib_prog_1 (host,atoi(argv[2])); 
    exit (0); 
}
